name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create dist folder
        run: mkdir -p dist

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: vcschroer
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: List workspace files recursively
        run: ls -Rla

      - name: List dist folder content
        run: ls -la dist || echo "dist folder does not exist"

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
