name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Create dist folder
        run: mkdir -p dist

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: vcschroer
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: List files in dist
        run: ls -la dist

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
